name: Release Crate

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write # To create GitHub Release
  id-token: write # REQUIRED for Trusted Publishing (OIDC)
  attestations: write # For SLSA Build Provenance

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
        
      - name: OpenID Connect Login
        uses: rust-lang/crates-io-auth-action@v1
        id: auth
        
      - name: Publish to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
